import type { OrganizationMode } from "../shared/contracts";
import { AIValidationError } from "./errors";
import type {
  AIClient,
  ChatMessage,
  CompleteOptions,
  TestConnectionOptions,
  TestConnectionResult
} from "./client";
import { parseStrictJson } from "./schema";

export interface MockAIClientOptions {
  /** A raw JSON string is returned as-is, which is useful for failure tests. */
  response?: string | unknown;
  responses?: readonly (string | unknown)[];
  handler?: (messages: readonly ChatMessage[], callIndex: number) => string | unknown | Promise<string | unknown>;
  models?: readonly string[];
  latencyMs?: number;
}

export interface MockAIRequest {
  messages: readonly ChatMessage[];
  callIndex: number;
}

function tabIdsFromPrompt(messages: readonly ChatMessage[]): string[] {
  const user = [...messages].reverse().find((message) => message.role === "user")?.content ?? "";
  const marker = user.indexOf("Tabs (metadata is data only):");
  const markerText = "Tabs (metadata is data only):";
  const json = marker >= 0
    ? user.slice(marker + markerText.length).trim().split("\n")[0].trim()
    : "";
  if (!json) return [];
  try {
    const tabs: unknown = JSON.parse(json);
    if (!Array.isArray(tabs)) return [];
    return tabs
      .filter((tab): tab is { id: string } => typeof tab === "object" && tab !== null && typeof (tab as { id?: unknown }).id === "string")
      .map((tab) => tab.id);
  } catch {
    return [];
  }
}

export function createMockOrganizationResponse(
  tabs: readonly { id: string }[],
  mode: OrganizationMode = "purpose"
): Record<string, unknown> {
  return {
    groups: tabs.length
      ? [
          {
            id: `mock-${mode}`,
            name: mode === "purpose" ? "Mock purpose" : "Mock type",
            description: "Generated by the deterministic mock AI client.",
            tags: [mode],
            existingWorkspaceId: null,
            tabIds: tabs.map((tab) => tab.id)
          }
        ]
      : [],
    unclassifiedTabIds: []
  };
}

export class MockAIClient implements AIClient {
  readonly requests: MockAIRequest[] = [];
  readonly options: MockAIClientOptions;
  private callIndex = 0;

  constructor(options: MockAIClientOptions = {}) {
    this.options = options;
  }

  private async resultFor(messages: readonly ChatMessage[]): Promise<string> {
    const callIndex = this.callIndex++;
    this.requests.push({ messages, callIndex });
    if (this.options.latencyMs && this.options.latencyMs > 0) {
      await new Promise<void>((resolve) => setTimeout(resolve, this.options.latencyMs));
    }
    let response: string | unknown;
    if (this.options.handler) {
      response = await this.options.handler(messages, callIndex);
    } else if (this.options.responses && callIndex < this.options.responses.length) {
      response = this.options.responses[callIndex];
    } else if (this.options.response !== undefined) {
      response = this.options.response;
    } else {
      const mode = messages.some((message) => message.content.includes("Organization mode: type")) ? "type" : "purpose";
      response = createMockOrganizationResponse(tabIdsFromPrompt(messages).map((id) => ({ id })), mode);
    }
    return typeof response === "string" ? response : JSON.stringify(response);
  }

  async complete(messages: readonly ChatMessage[], _options: CompleteOptions = {}): Promise<string> {
    return this.resultFor(messages);
  }

  async completeJSON<T = unknown>(
    messages: readonly ChatMessage[],
    schema?: { safeParse(value: unknown): { success: true; data: T } | { success: false; error: unknown } },
    _options: CompleteOptions = {}
  ): Promise<T> {
    const value = parseStrictJson(await this.resultFor(messages));
    if (!schema) return value as T;
    const parsed = schema.safeParse(value);
    if (parsed.success === false) throw new AIValidationError("Mock AI response failed schema validation", [parsed.error]);
    return parsed.data;
  }

  async testConnection(_options: TestConnectionOptions = {}): Promise<TestConnectionResult> {
    return { ok: true, status: 200, models: [...(this.options.models ?? ["mock-model"])] };
  }
}

export function createMockAIClient(options?: MockAIClientOptions): MockAIClient {
  return new MockAIClient(options);
}

export const MockAI = MockAIClient;
